target("quickjspp")
    before_build(function (target) 
        os.trycp("src/tp/quickjspp/cutils.h", "src/tp/inc/quickjspp/")
        os.trycp("src/tp/quickjspp/quickjs.h", "src/tp/inc/quickjspp/")
        os.trycp("src/tp/quickjspp/quickjs-libc.h", "src/tp/inc/quickjspp/")
        local file = io.open("src/tp/quickjspp/VERSION", "r")
        local vers = file:read()
        file:close()
        vars = vers:gsub("%s+", "")
        file = io.open("src/tp/inc/quickjspp/quickjs-version.h", "w+")
        file:write("#define QUICKJS_VERSION \"" .. vers .. "\"")
        file:close()
    end)
    set_kind("static")
    add_cxflags("-DJS_STRICT_NAN_BOXING")
    add_files("quickjspp/lib*.c", "quickjspp/quickjs*.c", "quickjspp/cutils.c")